#!/usr/bin/env bash
#
# install-secret-scan-hook.sh — install pre-commit hook that scans staged
#                               files for common secret patterns.
#
# Run once after clone:  ./scripts/install-secret-scan-hook.sh
#
# Patterns: Anthropic, Google, OpenAI, GitHub, AWS, Stripe, Slack, JWT,
# pgcrypto base64 keys, generic high-entropy tokens. Conservative
# (false positives lean toward blocking) — that's the right default.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOK="$ROOT/.git/hooks/pre-commit"

if [[ ! -d "$ROOT/.git" ]]; then
  echo "FAIL: not a git repository"
  exit 2
fi

cat > "$HOOK" <<'HOOK_EOF'
#!/usr/bin/env bash
#
# Lakshya pre-commit secret scan
# Generated by scripts/install-secret-scan-hook.sh — do not edit by hand.

set -euo pipefail

STAGED=$(git diff --cached --name-only --diff-filter=AM)
[[ -z "$STAGED" ]] && exit 0

# Skip lockfiles + .env.example (placeholders, not real keys)
FILTERED=$(echo "$STAGED" | grep -vE '(^|/)(package-lock\.json|pnpm-lock\.yaml|yarn\.lock|\.env\.example)$' || true)
[[ -z "$FILTERED" ]] && exit 0

PATTERNS=(
  'sk-ant-api[a-zA-Z0-9_-]{20,}'              # Anthropic
  'sk-proj-[a-zA-Z0-9_-]{20,}'                # OpenAI project key
  'sk-[a-zA-Z0-9]{40,}'                       # OpenAI legacy
  'AIza[0-9A-Za-z_-]{35}'                     # Google API key
  'ghp_[a-zA-Z0-9]{36}'                       # GitHub PAT
  'gho_[a-zA-Z0-9]{36}'                       # GitHub OAuth
  'AKIA[0-9A-Z]{16}'                          # AWS access key
  'rk_live_[a-zA-Z0-9]{24,}'                  # Stripe restricted
  'sk_live_[a-zA-Z0-9]{24,}'                  # Stripe secret
  'xoxb-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24,32}'  # Slack bot
  'eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}'  # JWT
  'apify_api_[a-zA-Z0-9]{30,}'                # Apify
  '-----BEGIN [A-Z ]+PRIVATE KEY-----'        # Private keys
)

FOUND=0
while IFS= read -r file; do
  [[ -z "$file" || ! -f "$file" ]] && continue
  for pattern in "${PATTERNS[@]}"; do
    if git show ":$file" 2>/dev/null | grep -E -- "$pattern" >/dev/null; then
      echo "✗ Possible secret in: $file"
      git show ":$file" | grep -nE -- "$pattern" | head -3 | sed 's/^/    /'
      FOUND=1
    fi
  done
done <<< "$FILTERED"

if [[ "$FOUND" -ne 0 ]]; then
  echo ""
  echo "Commit blocked. If these are NOT real secrets, prefix with placeholder text"
  echo "or move into .env.local. To bypass once: git commit --no-verify (audit log will record)."
  exit 1
fi
HOOK_EOF

chmod +x "$HOOK"
echo "✓ Pre-commit hook installed at .git/hooks/pre-commit"
echo "  Detects: Anthropic, OpenAI, Google, GitHub, AWS, Stripe, Slack, JWT, Apify, private keys"
echo "  Skips:   package-lock.json, pnpm-lock.yaml, yarn.lock, .env.example"
